language: php

php:
  - 8.0
  - 8.1
  - 8.2
  - 8.3
  - 8.4

script:
  - composer run test
  - composer run check

before_script:
  - travis_retry composer self-update
  - travis_retry composer clear-cache
  - travis_retry composer update
  - mkdir -p build/logs

after_success:
  - travis_retry php vendor/bin/php-coveralls --verbose --coverage-clover build/logs/clover.xml
